### ISSUE TITLE
Unrecognized entity ID 5

### ISSUE THREAD

**Issue by bcwhite-code** [nyurik/fatul#9]
```
0eNqVkd1qwzAMhV+l6FqBOIvbOZd9hsEuQghxJopYYgfH7VaK3312wpbCfmD4wtKx9B0h30APZ5ocG99qa1+hum3KDFV9l6Y37q1Z5ZlPphuSZrqRoALNp4wG6r3jPpvsQBAQ2LzQO1QiNAhkPHumtX1Jrq05j5pcLMDfMQiTnWOnNckt0jKRy0eEa4wOqgwBv+GKf+KKwx0ujvrGbpmzFiiwQNFgne54lkjGSDaxjj2NyeRrRQhDpymuBZ4jYvdEc9Iu5ObFT+4LVSolH1Qp97nYFpSHH2jZ8iMbMtF2x1Xres8Xaj/b//AIH4mfmxo=
```

```
fatul: error: Unrecognized entity ID 5 in Wire Test in wires[2]

Traceback (most recent call last):
  File "/home/bcwhite/bin/fatul", line 157, in main
    args.func(args)
  File "/home/bcwhite/bin/fatul", line 170, in decode_cmd
    decode(args.source, args.destination, args.verbose, args.compact, args.sort, args.ids,
  File "/home/bcwhite/bin/fatul", line 191, in decode
    data = processor.decode(json_text)
  File "/home/bcwhite/bin/fatul", line 293, in decode
    self.process_ids(data, to_abs_ids=False)
  File "/home/bcwhite/bin/fatul", line 312, in process_ids
    self._process_ids_rec(data, to_abs_ids)
  File "/home/bcwhite/bin/fatul", line 332, in _process_ids_rec
    self._process_ids_rec(val, to_abs_ids)
  File "/home/bcwhite/bin/fatul", line 332, in _process_ids_rec
    self._process_ids_rec(val, to_abs_ids)
  File "/home/bcwhite/bin/fatul", line 336, in _process_ids_rec
    self._process_ids_rec(val, to_abs_ids)
  File "/home/bcwhite/bin/fatul", line 322, in _process_ids_rec
    bp.update_references()
  File "/home/bcwhite/bin/fatul", line 598, in update_references
    self.ids.update_ref_list(wires, f"wires[{idx}]", "wires")
  File "/home/bcwhite/bin/fatul", line 489, in update_ref_list
    data.append(self._make_rel_id(entity_number, val, typ))
  File "/home/bcwhite/bin/fatul", line 507, in _make_rel_id
    raise ValueError(f"Unrecognized entity ID {to_entity_id} in {self.label}{extra}")
ValueError: Unrecognized entity ID 5 in Wire Test in wires[2]
```

**Comment by nyurik** [comment]
@bcwhite-code what was the command you used with the above?

**Comment by nyurik** [comment]
Thanks, your test proved to be far more useful than my bigger one because it highlighted my mis-understanding of the `wires`.  I fixed it in https://github.com/nyurik/fatul/commit/9b916ff8e0cb0f5b66d48339f4ec31fa02bdc718 -- see comment there with my understanding how the `wires` section works
